# Generated by Django 3.2.5 on 2021-07-08 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 7, 8, 19, 58, 32, 90180, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
