# Generated by Django 3.2.5 on 2021-07-09 17:22

from django.db import migrations, models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
    ]
